# Generated by Django 3.2.4 on 2021-06-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driver_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_no', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('rick_no', models.CharField(max_length=50)),
                ('your_image', models.ImageField(upload_to='static/img/driver_detail')),
                ('rick_image', models.ImageField(upload_to='static/img/driver_detail')),
                ('date_joined', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
