# Generated by Django 3.1 on 2020-08-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabdriver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_detail',
            name='date_joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver_detail',
            name='rick_image',
            field=models.ImageField(upload_to='static/img/driver_detail'),
        ),
        migrations.AlterField(
            model_name='driver_detail',
            name='your_image',
            field=models.ImageField(upload_to='static/img/driver_detail'),
        ),
    ]
