# Generated by Django 3.1 on 2020-08-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabdriver', '0002_auto_20200806_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_detail',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
