# Generated by Django 3.2.4 on 2021-06-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabdriver', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(blank=True, max_length=50, null=True)),
                ('c_phone_no', models.IntegerField(blank=True, null=True)),
                ('from_desti', models.CharField(max_length=50)),
                ('to_desti', models.CharField(max_length=50)),
                ('date_to', models.CharField(max_length=50)),
                ('time_to', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50)),
                ('c_phone_no', models.CharField(max_length=50)),
                ('d_phone_no', models.CharField(max_length=50)),
                ('from_desti', models.CharField(blank=True, max_length=50, null=True)),
                ('to_desti', models.CharField(blank=True, max_length=50, null=True)),
                ('date_to', models.CharField(blank=True, max_length=50, null=True)),
                ('time_to', models.CharField(blank=True, max_length=50, null=True)),
                ('order_status', models.CharField(blank=True, max_length=50, null=True)),
                ('dname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabdriver.driver_detail')),
            ],
        ),
    ]
