# Generated by Django 3.1 on 2020-08-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
                ('from_desti', models.CharField(max_length=50)),
                ('to_desti', models.CharField(max_length=50)),
                ('date_to', models.CharField(max_length=50)),
                ('time_to', models.CharField(max_length=50)),
            ],
        ),
    ]
