# Generated by Django 3.1 on 2020-08-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_order_cname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
