# Generated by Django 3.1 on 2020-08-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('dname', models.CharField(max_length=50)),
                ('c_phone_no', models.CharField(max_length=50)),
                ('d_phone_no', models.CharField(max_length=50)),
                ('from_desti', models.CharField(max_length=50)),
                ('to_desti', models.CharField(max_length=50)),
                ('date_to', models.CharField(max_length=50)),
                ('time_to', models.CharField(max_length=50)),
            ],
        ),
    ]
