# Generated by Django 3.1 on 2020-08-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20200819_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_to',
            field=models.CharField(max_length=50),
        ),
    ]
