# Generated by Django 3.1 on 2020-08-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20200819_1831'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer_route',
        ),
    ]
