# Generated by Django 3.1 on 2020-08-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_delete_customer_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='c_phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
