# Generated by Django 3.1 on 2020-08-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20200819_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('In_Transit', 'In Transit'), ('Complete', 'Complete')], max_length=50, null=True),
        ),
    ]
