# Generated by Django 3.0.8 on 2020-07-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200716_1440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='Customer',
        ),
    ]
