# Generated by Django 3.0.8 on 2020-07-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200716_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('Area', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
